name: deploy

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-web:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "20.10.0"

      - name: cache deps
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install deps
        run: npm i
        working-directory: ./web/dbdb

      - name: build app
        run: npm run build
        working-directory: ./web/dbdb

      - name: save assets
        uses: actions/upload-artifact@v4
        with:
          name: web_assets
          path: ./web/dbdb/build

  python-tests:
    name: python tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: show python version
        run: python -c "import sys; print(sys.version)"

      - name: pytest
        env:
          DBDB_GSHEETS_API_KEY: ${{ secrets.DBDB_GSHEETS_API_KEY }}
          DBDB_OPENAI_API_KEY: ${{ secrets.DBDB_OPENAI_API_KEY }}
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          pytest -v tests/

  deploy:
    name: deploy
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    needs: [build-web, python-tests]

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: load assets
        uses: actions/download-artifact@v4
        with:
          name: web_assets
          path: build

      - name: relocate assets
        run: mv build/ $GITHUB_WORKSPACE/web/dbdb/build/

      - name: list assets
        run: ls -R $GITHUB_WORKSPACE/web/dbdb/build

      - run: flyctl deploy -a dbdb --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
